### ISSUE TITLE
2 dlls missing when building DemoParser-UI

### ISSUE THREAD

**Issue by bselders** [CSGO-Analysis/CSGO-Analyzer#2]
CSGO-Analyzer-master\DemoParser\bin\Debug\DemoParser-Core.dll & CSGO-Analyzer-master\DemoParser-Model\bin\Debug\DemoParser-Model.dll aren't found when building the DemoParser-UI.sln file.

(also if you are still active I wanted to chat about how to get this working - you can email me at seldersbrendan@gmail.com)

**Comment by thiagohrm** [comment]
i would like to have this too

**Comment by 0BuRner** [comment]
Hi,
This library is out of date.
You should look at https://github.com/akiver/CSGO-Demos-Manager and/or https://github.com/StatsHelix/demoinfo/

Regards
