### ISSUE TITLE
Dictionary missign key

### ISSUE THREAD

**Issue by ZUBAT** [CSGO-Analysis/CSGO-Analyzer#3]
Hello. I parce demo and have many errors on dictionary
System.Collections.Generic.KeyNotFoundException: Данный ключ отсутствует в словаре.
   в System.ThrowHelper.ThrowKeyNotFoundException()
   в System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   в DemoParser_Core.Packets.Handlers.GameEventHandler.TryApplyMessage(IExtensible message, DemoParser parser) 

Can you help me?

**Comment by 0BuRner** [comment]
Hi,
This library is out of date. 
You should look at https://github.com/akiver/CSGO-Demos-Manager and/or https://github.com/StatsHelix/demoinfo/

Regards
